
# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
    auth_token_user_provider:
        class: EveryCheck\ApiRestUserBundle\Security\AuthTokenUserProvider
        arguments: ["@auth_token_repository", "@user_repository"]
        public:    false

    auth_token_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["UserBundle:AuthToken"]
        public: true

    user_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["UserBundle:User"]
        public: true

    auth_token_authenticator:
        class:     EveryCheck\ApiRestUserBundle\Security\AuthTokenAuthenticator
        arguments: ["@security.http_utils","@response","%secret%"]
        public:    false
        
    password_generator:
        class:     EveryCheck\ApiRestUserBundle\Service\UserPasswordGenerator
        arguments: ["@security.password_encoder","%generate_password%"]
        public: true
        
    response:
        class: EveryCheck\ApiRest\Utils\ResponseBuilder
        arguments: ["@jms_serializer"]
        public: true
        
    acl_manager:
        class: EveryCheck\SimpleAclBundle\Service\AclManager
        arguments: ["@doctrine.orm.entity_manager","@event_dispatcher","@annotation_reader"]
        public: true

    acl_doctrine_subscriber:
        class: EveryCheck\SimpleAclBundle\EventListener\CreateSchemaListener
        arguments: ["@acl_manager",'UserBundle\Entity\User']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    acl_user_population_listener:
        class: DemoBundle\EventListener\UserPopulationListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: acl_event.request_population , method: onPostedResquest }


